version: 0.2

env:
  variables:
  TF_IN_AUTOMATION: 1

phases:
  pre-build:
    commands:
      - make install
  build:
    commands:
      - make linting
      - make terragrunt
  post_build:
    commdands:
      - echo Build completed on `date`
    
reports:
  checkov-reports:
    files:
      - "/checkov.xml"
    base-directory: ".reports"
    file-format: JunitXml
    discard-paths: no

